"""add_image_url_to_messages

Revision ID: 8e8cee911724
Revises: d1afd9769797
Create Date: 2026-02-11 22:13:17.148185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8cee911724'
down_revision: Union[str, None] = 'd1afd9769797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'image_url')
    # ### end Alembic commands ###
